#AUTH SETTINGS
#-----------------------------------------------------
#Minimum password length
minPasswordLength: 5

#Sign up disabled
disableRegister: false

#Default Server Prefix
default-prefix: "[ 서버 ]"

#Time to wait for authentication
authenticateTimeout: 60

#NormalAuth
authentication: "NormalAuth"
#-----------------------------------------------------

#CUSTOMPACKET SETTINGS
#-----------------------------------------------------
#Whether using a custom packet
#type : null || true || false
usecustompacket: null

#Set servermode
#type : null || master || slave
servermode: null

passcode: null
masterip: null
masterport: null
#-----------------------------------------------------